### ISSUE TITLE
Member - controller, service, repository

### ISSUE THREAD

**Issue by ptkeb** [6-dobbies/Black-And-White#11]

**Comment by YoojinMa** [comment]
- [x] getMemberByIdx() : 회원 한 명 idx로 조회

- [x] getMemberByNickname() : 회원 한 명 nickname으로 조회

- [x] getMemberByNicknameCon() : 회원 한 명 nickname 일부로 조회

- [x] getMemberAll() : 회원 전체 조회

- [x] saveMember() : 회원 저장

- [x] updateMember() : 회원 수정

- [x] deleteMember() : 회원 탈퇴
